# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10d6eea4202dda8463d4a2354dc8293f273d3e141d4e6b5c2ec10fc28a67e7ca1f12d510fab829d691cf900ecc51c075333dcd4699d3c0709544ae662486333f

test:
  secret_key_base: 88d5af17ae47b7c101f8dc618ca6df4defb8ed21856c5c9a754ec2e0f42cdb204a39839775ea9198537f55affa3de9bf65f8655fcf4ed25c5fed10598e2763ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
